### ISSUE TITLE
Usage with babel

### ISSUE THREAD

**Issue by amilajack** [roman01la/closure-compiler-handbook#1]
Most users are probably using babel because it has more coverage of ES6 than closure compiler. Could there be a section on this?

**Comment by chicoxyzzy** [comment]
What do you mean by usage with Babel? If your use Babel along with Closure Compiler, your pipeline is likely looks like
ESnext -> Babel -> ES5 -> Closure Compiler -> compiled ES5

so Babel doesn't affect Closure Compiler in any way

**Comment by amilajack** [comment]
I was under the impression that optimizing compiled babel code would be more difficult to optimize than es6 source code

**Comment by roman01la** [comment]
Hi @amilajack 

If source files are transpiled directly with Babel, without bundling via Webpack/Browserify, whatever, then it shouldn't be different. What makes it harder for Closure Compiler to optimize code is closure wrappers for every module in a bundle produced by Webpack and Browserify.

Is it something you wanted to be documented?

**Comment by amilajack** [comment]
I see. Thanks for clarifying
