### ISSUE TITLE
How to reference external/compiled code

### ISSUE THREAD

**Issue by dmitriid** [roman01la/closure-compiler-handbook#3]
This handbook is absolutely brilliant, and should definitely replace the official "documentation" :)

A minor issue from my point of view: 

Advanced compilation -> Referencing external code and Referencing compiled code

> If you want to use globally defined variables and functions in your code safely, you must tell the compiler about those references.
> If you are about to build a library that exports to global scope, you must tell the compiler about variables that should be exported safely.

Can you add a small section on how to tell the compiler about references and variables?

**Comment by roman01la** [comment]
@dmitriid Hi! I've added a section explaining [externs](https://github.com/roman01la/closure-compiler-handbook#externs). For referencing compiled code there was already one, I've added a reference to it also [Exporting to global scope](https://github.com/roman01la/closure-compiler-handbook#exporting-to-global-scope).

Note that these two doesn't cover JavaScript modules.

Also FYI, [Closure Compiler documentation](https://developers.google.com/closure/compiler/) exists and it very good, IMHO 🙂

**Comment by dmitriid** [comment]
Thanks!
